name: "Deploy GH Repo to S3"

on:
  workflow_dispatch:
    branches:
      - main
    inputs:
      env_filter:
        required: true
        type: choice
        description: Which environment would you like to deploy to?
        options:
        - DEV
        - SIT
        - PRE_PROD
        - PROD

jobs:
  call-test-workflow-module:
    name: Test Remote
    uses: efairgrieveorg/workflow-templates/.github/workflows/deploy.yml@main
    secrets: inherit
    with:
      passed_env_filter: ${{ github.event.inputs.env_filter }}